# Generated by Django 3.0.8 on 2020-07-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='thumbnail',
            field=models.ImageField(default='service_default.jpg', upload_to='service'),
        ),
    ]
