# Generated by Django 3.0.8 on 2020-08-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
