# Generated by Django 3.0.8 on 2020-09-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_offer_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
    ]
