# Generated by Django 3.0.8 on 2020-07-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='certification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='education',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
