# Generated by Django 3.0.8 on 2020-08-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_phonebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='occupation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
